random_seed: 2024
environment_name: cifar100
num_steps: 1.0e+6
num_eval: 101

agent_params:

    'pg':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {}

    'pg_mmd':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {mmd: .0}

    'pg_ent':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {entropy: .0}

    'pg_l1':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l1: .0}

    'pg_l2':
        loss_type: pg
        temperature: 1.
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l2: .0}

