random_seed: 2024
environment_name: mnist
num_steps: 1.0e+5
num_eval: 101


agent_params:

    'q':
        loss_type: q
        temperature: .1
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {}

    'q_l1_00001':
        loss_type: q
        temperature: .1
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l1: .00001}

    'q_l1_00002':
        loss_type: q
        temperature: .1
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l1: .00002}

    'q_l1_00003':
        loss_type: q
        temperature: .1
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l1: .00003}

    'q_l1_00004':
        loss_type: q
        temperature: .1
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l1: .00004}

    'q_l1_00005':
        loss_type: q
        temperature: .1
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l1: .00005}

    'q_l1_00006':
        loss_type: q
        temperature: .1
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l1: .00006}

    'q_l1_00007':
        loss_type: q
        temperature: .1
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l1: .00007}

    'q_l1_00008':
        loss_type: q
        temperature: .1
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l1: .00008}

    'q_l1_00009':
        loss_type: q
        temperature: .1
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l1: .00009}

    'q_l1_00010':
        loss_type: q
        temperature: .1
        batch_size: 100
        optimizer: {name: Adam, learning_rate: 1.0e-3}
        regularization: {l1: .00010}

